<a href="https://colab.research.google.com/github/shashwat-2077/ComputerVisionWeek_AI/blob/main/Drawing_Shapes_and_Lines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cv2

In [ ]:
img = np.zeros((512,512), np.uint8)

In [ ]:
#img[ : ] = 255, 0, 0 (B,G,R)
#cv2.line(img, Start_Point, end_point, oclour, thickness)

In [ ]:
#Diagonal Line
cv2.line(img, (0,0), (img.shape[1], img.shape[0]), (255,0,0), 3)

array([[255, 255, 255, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [ ]:
cv2.imshow("Line", img)
cv2.waitKey(0)

DisabledFunctionError: ignored

In [ ]:
#rectangle
#cv2.(source, (0,0), (250,350), (0,0,255), 4)

cv2.rectangle(img, (0,0), (250,350), (255,0,0), 4)

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [ ]:
cv2.imshow("Rectangle", img )
cv2.waitKey(0)

In [ ]:
cv2.circle(img, (400,50), 30, (255,0,0), 6)
#Parameters are : source, centre, radius, colour, thickness

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [ ]:
cv2.imshow("Circle", img)
cv2.waitKey(0)

In [ ]:
img2 = np.zeros((512,512), np.uint8)

In [ ]:
cv2.putText(img, "CV Week!!", (300,150), cv2.FONT_HERSHEY_DUPLEX, 3, (150,0,0), 1)
#Parameters are : source, text, start_point, font, scale, colour, thickness 

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [ ]:
cv2.imshow("Text", img2)
cv2.waitKey(0)